id: mysubflow
namespace: example

inputs: 
  - id: json
    type: JSON

tasks: 
  - id: debug
    type: io.kestra.plugin.core.log.Log
    message: "{{ inputs.json }}"

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: 30 6 * * *
    disabled: true