id: realtime_pubsub
namespace: example

tasks:
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: "Received: {{ trigger.data | base64decode }}"

triggers:
  - id: trigger
    type: io.kestra.plugin.gcp.pubsub.RealtimeTrigger
    projectId: kestra-sandbox
    topic: test-topic
    subscription: test-topic-sub
    serviceAccount: "{{ secret('GOOGLE_SA') }}"
    disabled: true